#!/bin/bash

AWS_PROFILE=default
AWS_REGION=us-east-1
ECR_PREFIX=eric-test

containers=(elasticsearch express nginx)
for container in "${containers[@]}"
do
  aws --profile $AWS_PROFILE ecr create-repository --repository-name $ECR_PREFIX/$container
done
